
# A string specifying the project reference ID
project_id = "wgnvrxubwifcscrbkimm"

[functions.create-checkout]
verify_jwt = true

[functions.webhook-handler]
verify_jwt = false

[functions.get-subscription]
verify_jwt = true
