
project_id = "wgnvrxubwifcscrbkimm"
[api]
enabled = true
port = 54321
[db]
port = 54322
[studio]
port = 54323
[functions]
[functions.create-checkout]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
