-- Fix extension versions to use recommended defaults
ALTER EXTENSION IF EXISTS "uuid-ossp" UPDATE;
ALTER EXTENSION IF EXISTS "pgcrypto" UPDATE; 
ALTER EXTENSION IF EXISTS "pgjwt" UPDATE;
ALTER EXTENSION IF EXISTS "pg_stat_statements" UPDATE;
ALTER EXTENSION IF EXISTS "pg_graphql" UPDATE;
ALTER EXTENSION IF EXISTS "pg_jsonschema" UPDATE;
ALTER EXTENSION IF EXISTS "wrappers" UPDATE;
ALTER EXTENSION IF EXISTS "vault" UPDATE;